export interface SeedCert {
  id: string;
  certificateId: string;
  companyName: string;
  siteName: string;
  location: string;
  country: string;
  issueDate: string;
  expiryDate: string;
  status: "valid" | "expired" | "suspended";
  scopeStatement: string;
}

export const CERT_SEED: SeedCert[] = [
  { id: "1", certificateId: "HPDC-ESG-2024-001", companyName: "Saudi Aramco", siteName: "Dhahran Headquarters", location: "Dhahran, Eastern Province, Saudi Arabia", country: "Saudi Arabia", issueDate: "2024-01-15", expiryDate: "2027-01-14", status: "valid", scopeStatement: "Environmental management, social responsibility, and corporate governance practices across upstream oil and gas operations, including environmental impact assessments, community engagement programs, and board-level governance structures." },
  { id: "2", certificateId: "HPDC-ESG-2024-002", companyName: "Saudi Electricity Company (SEC)", siteName: "Riyadh Power Plant No. 10", location: "Riyadh, Riyadh Province, Saudi Arabia", country: "Saudi Arabia", issueDate: "2024-03-01", expiryDate: "2027-02-28", status: "valid", scopeStatement: "Sustainable energy generation and distribution operations, including renewable energy integration, emissions monitoring, and employee occupational health and safety programs." },
  { id: "3", certificateId: "HPDC-ESG-2023-015", companyName: "SABIC", siteName: "Al Jubail Industrial City Plant", location: "Al Jubail, Eastern Province, Saudi Arabia", country: "Saudi Arabia", issueDate: "2021-06-10", expiryDate: "2024-06-09", status: "expired", scopeStatement: "Petrochemical manufacturing operations covering environmental compliance, chemical waste management, and employee welfare programs across Al Jubail production facilities." },
  { id: "4", certificateId: "HPDC-ESG-2024-008", companyName: "Ma'aden (Saudi Arabian Mining Company)", siteName: "Wa'ad Al Shamal Phosphate Complex", location: "Northern Borders Province, Saudi Arabia", country: "Saudi Arabia", issueDate: "2023-09-01", expiryDate: "2026-08-31", status: "suspended", scopeStatement: "Mining and minerals processing operations, land reclamation, environmental restoration, and occupational health management across phosphate extraction and processing facilities." },
  { id: "5", certificateId: "HPDC-ESG-2024-011", companyName: "stc (Saudi Telecom Company)", siteName: "Riyadh HQ — Digital Infrastructure Division", location: "Riyadh, Riyadh Province, Saudi Arabia", country: "Saudi Arabia", issueDate: "2024-05-20", expiryDate: "2027-05-19", status: "valid", scopeStatement: "Digital infrastructure operations, data center energy efficiency, employee diversity programs, and cybersecurity governance frameworks aligned with Vision 2030 digital economy objectives." },
  { id: "6", certificateId: "HPDC-ESG-2024-020", companyName: "Emirates Global Aluminium (EGA)", siteName: "Jebel Ali Smelting Complex", location: "Jebel Ali, Dubai, United Arab Emirates", country: "United Arab Emirates", issueDate: "2024-02-10", expiryDate: "2027-02-09", status: "valid", scopeStatement: "Primary aluminium smelting operations covering carbon footprint reduction, water recycling initiatives, community development programs, and supply chain transparency reporting." },
  { id: "7", certificateId: "HPDC-ESG-2023-031", companyName: "ADNOC Logistics & Services", siteName: "Abu Dhabi Marine Terminal", location: "Abu Dhabi, United Arab Emirates", country: "United Arab Emirates", issueDate: "2022-11-01", expiryDate: "2025-10-31", status: "expired", scopeStatement: "Marine logistics, port operations, and petroleum product distribution covering vessel emission monitoring, spill prevention protocols, and port community welfare programs." },
  { id: "8", certificateId: "HPDC-ESG-2024-035", companyName: "Kuwait Finance House (KFH)", siteName: "Shuwaikh Central Operations", location: "Shuwaikh, Kuwait City, Kuwait", country: "Kuwait", issueDate: "2024-06-01", expiryDate: "2027-05-31", status: "valid", scopeStatement: "Islamic banking and financial services operations including green financing products, ethical investment screening, financial inclusion programs, and Sharia-compliant ESG governance frameworks." },
  { id: "9", certificateId: "HPDC-ESG-2024-042", companyName: "QatarEnergy", siteName: "Ras Laffan LNG Facility", location: "Ras Laffan Industrial City, Qatar", country: "Qatar", issueDate: "2024-04-15", expiryDate: "2027-04-14", status: "valid", scopeStatement: "Liquefied natural gas production and export operations, including greenhouse gas reduction targets, flare minimization programs, worker welfare standards, and independent ESG audit frameworks." },
  { id: "10", certificateId: "HPDC-ESG-2023-048", companyName: "Alba (Aluminium Bahrain)", siteName: "Bahrain Smelter — Line 6 Expansion", location: "Askar, Southern Governorate, Bahrain", country: "Bahrain", issueDate: "2023-07-01", expiryDate: "2026-06-30", status: "valid", scopeStatement: "Primary aluminium production with focus on energy efficiency upgrades, water desalination sustainability, occupational health management, and board diversity in line with GCC ESG standards." },
  { id: "11", certificateId: "HPDC-ESG-2024-055", companyName: "Jordan Phosphate Mines Company", siteName: "Aqaba Phosphate Port Terminal", location: "Aqaba Special Economic Zone, Jordan", country: "Jordan", issueDate: "2024-01-20", expiryDate: "2027-01-19", status: "valid", scopeStatement: "Phosphate mining, processing, and port export operations covering land rehabilitation, dust suppression programs, mine community development, and export-chain environmental compliance." },
  { id: "12", certificateId: "HPDC-ESG-2023-060", companyName: "Egyptian Electricity Holding Company", siteName: "Cairo North Power Station", location: "Shubra El-Khema, Cairo Governorate, Egypt", country: "Egypt", issueDate: "2022-08-15", expiryDate: "2025-08-14", status: "expired", scopeStatement: "Electric power generation and grid distribution covering emissions reduction commitments, water usage optimization, and community energy access programs in underserved areas." },
  { id: "13", certificateId: "HPDC-ESG-2024-067", companyName: "Oman LNG", siteName: "Qalhat LNG Plant", location: "Sur, Al Sharqiyah, Oman", country: "Oman", issueDate: "2024-07-01", expiryDate: "2027-06-30", status: "valid", scopeStatement: "LNG liquefaction and export terminal operations covering methane emission controls, marine biodiversity protection, local content development, and independent ESG reporting aligned with international standards." },
  { id: "14", certificateId: "HPDC-ESG-2024-075", companyName: "National Shipping Company of Saudi Arabia (Bahri)", siteName: "Jeddah Islamic Port — Marine Operations Hub", location: "Jeddah, Makkah Province, Saudi Arabia", country: "Saudi Arabia", issueDate: "2024-08-10", expiryDate: "2027-08-09", status: "valid", scopeStatement: "Maritime shipping and logistics operations, covering vessel fuel efficiency, ballast water management, port community relations, and decarbonization roadmap in line with IMO 2050 strategy." },
  { id: "15", certificateId: "HPDC-ESG-2023-080", companyName: "Riyad Bank", siteName: "Riyadh Main Branch Operations", location: "Riyadh, Riyadh Province, Saudi Arabia", country: "Saudi Arabia", issueDate: "2023-04-01", expiryDate: "2026-03-31", status: "valid", scopeStatement: "Banking and financial services operations including green bond issuance programs, responsible lending practices, digital branch carbon footprint reduction, and employee well-being and governance disclosure." },
  { id: "16", certificateId: "HPDC-ESG-2024-085", companyName: "Taqa (Abu Dhabi National Energy Company)", siteName: "Shuweihat S3 Power & Water Facility", location: "Shuweihat, Abu Dhabi, United Arab Emirates", country: "United Arab Emirates", issueDate: "2024-02-28", expiryDate: "2027-02-27", status: "valid", scopeStatement: "Power generation and water desalination operations covering GHG emissions monitoring, water discharge management, workforce health programs, and ESG-aligned capital expenditure reporting." },
  { id: "17", certificateId: "HPDC-ESG-2024-092", companyName: "Dur Hospitality", siteName: "Mövenpick Hotel Riyadh Operations", location: "Riyadh, Riyadh Province, Saudi Arabia", country: "Saudi Arabia", issueDate: "2024-09-01", expiryDate: "2027-08-31", status: "valid", scopeStatement: "Hotel and hospitality services operations including energy and water conservation programs, food waste reduction, cultural heritage preservation, and responsible supply chain procurement practices." },
  { id: "18", certificateId: "HPDC-ESG-2023-099", companyName: "Al Rajhi Bank", siteName: "Headquarters — Riyadh Central Operations", location: "Riyadh, Riyadh Province, Saudi Arabia", country: "Saudi Arabia", issueDate: "2023-11-15", expiryDate: "2026-11-14", status: "valid", scopeStatement: "Islamic banking operations encompassing Sharia-compliant ESG governance, green sukuk programs, financial literacy and inclusion initiatives, and digital transformation sustainability." },
];

export function findSeedCert(certId: string): SeedCert | undefined {
  return CERT_SEED.find(c => c.certificateId === certId);
}
